version: '3.1'

services:
  mongo:
    image: mongo:7.0
    restart: always
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - ${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}