version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: node-express
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: joel
      MONGO_INITDB_ROOT_PASSWORD: secreto