###
POST http://localhost:3200/api/auth/singup
Content-Type: application/json

{
  "nombre": "Sandro",
  "email": "sandro@email.com",
  "password": "secreto"
}

### 
POST http://localhost:3200/api/auth/login
Content-Type: application/json

{
  "email": "shakira@email.com",
  "password": "secreto"
}

###
POST http://localhost:3200/api/auth/logout