@url = http://localhost:3200/api

###
POST {{url}}/auth/singup
Content-Type: application/json

{
  "nombre": "Joel",
  "email": "joel@email.com",
  "password": "joelsecreto",
  "roles": ["administrador", "moderador", "usuario"]
}

### 
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "shakira@email.com",
  "password": "secreto"
}

###
POST {{url}}/auth/logout