###
POST http://localhost:3200/api/auth/singup
Content-Type: application/json

{
  "nombre": "Joel",
  "email": "joel@email.com",
  "password": "secreto",
  "roles": ["administrador", "moderador", "usuario"]
}

### 
POST http://localhost:3200/api/auth/login
Content-Type: application/json

{
  "email": "shakira@email.com",
  "password": "secreto"
}

###
POST http://localhost:3200/api/auth/logout