@url = http://localhost:3200/api

###
GET http://localhost:3200
###
POST http://localhost:3200
###
PUT http://localhost:3200
###
DELETE http://localhost:3200

###
GET {{url}}/usuarios

###
GET {{url}}/usuarios/65601fa44fc98e4cd29779f5

###
POST {{url}}/usuarios
Content-Type: application/json

{
  "nombre": "Natali",
  "email": "natali@email.com",
  "password": "natalisecreto",
  "roles": ["moderador", "usuario"]
}

###
DELETE {{url}}/usuarios/65615605ad4217d7fdf21319
x-acces-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjE1MDg3MzcwNmUxZmUxM2QwYTZkYyIsImlhdCI6MTcwMDg3OTQ2OCwiZXhwIjoxNzAwOTY1ODY4fQ.nre29kQVQkg3J2oT30ntRk_Rf81W0DwcS5G71-8Wl7s

###
PATCH {{url}}/usuarios/655ce62ff0cddaecbc9f09b0
Content-Type: application/json

{
  "passwordHash": "caruchasecreto"
}