@url = http://localhost:3200/api

###
GET http://localhost:3200
###
POST http://localhost:3200
###
PUT http://localhost:3200
###
DELETE http://localhost:3200

###
GET {{url}}/usuarios

###
GET {{url}}/usuarios/65601fa44fc98e4cd29779f5

###
POST {{url}}/usuarios
Content-Type: application/json

{
  "nombre": "Natali",
  "email": "natali@email.com",
  "password": "natalisecreto",
  "roles": ["moderador", "usuario"]
}

###
DELETE {{url}}/usuarios/655b9882b3c3b094401be6c0
x-acces-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NjE0ZDk5NGIzNmMwZTk3Zjk3MjY4ZSIsImlhdCI6MTcwMDg3NTY3MywiZXhwIjoxNzAwOTYyMDczfQ.yw6N9ip9ziONzcaFbL0uESz13v6nEVKqLsizLx_9nI4

###
PATCH {{url}}/usuarios/655ce62ff0cddaecbc9f09b0
Content-Type: application/json

{
  "passwordHash": "caruchasecreto"
}