GET http://localhost:3200
###
POST http://localhost:3200
###
PUT http://localhost:3200
###
DELETE http://localhost:3200

###
GET http://localhost:3200/api/usuarios

###
GET http://localhost:3200/api/usuarios/655b95402157f2ba244aae9f

###
POST http://localhost:3200/api/usuarios
Content-Type: application/json

{
  "nombre": "Sandia",
  "email": "sandia@email.com",
  "admin": 3245234
}

###
DELETE http://localhost:3200/api/usuarios/655baa6dccd900ce5237d33f

###
PATCH http://localhost:3200/api/usuarios/23-84hdafsh;kdf
Content-Type: application/json

{
  "nombre": "Sandia",
  "email": "sandia@email.com",
  "admin": 3245234
}